@echo off

REM To use this batch file with any of your projects, just set this name
REM to the project you are working on.  It will do the rest.

set APPNAME=iManager_Java


REM This batch file should be located in the root of your main development folder.
REM It will zip up all the files in the folder, including all subdirectories and files in
REM these subdirectories.  It will remember the subdirectory names and where the
REM the files go when you unzip the archive.  Any filenames that are listed in the
REM file called excludelist.txt will not be included in the zip file.  You should put the names
REM and extensions of files that are generated by compilation and linking.  These files are
REM not needed and eliminating them from the backup will save a considerable amount of space.
REM The output will be a single zip file having the name specified by APPNAME and the current
REM date and time.  You will need to have the WinZip command line support installed on your computer.

REM Get the current date.
for /f "tokens=1,2" %%u in ('date /t') do set d=%%v
for /f "tokens=1" %%u in ('time /t') do set t=%%u
if "%t:~1,1%"==":" set t=0%t%
set timestr=%d:~6,4%-%d:~3,2%-%d:~0,2%_%t:~0,2%%t:~3,2%

set FILENAME=%APPNAME%_Backup_%timestr%

REM C:\Progra~2\WinZip\wzzip -siman123 -ycAES256 -rP -eX -o -X@excludelist.txt  %FILENAME% *.*
7z a %FILENAME%.7z -xr!thirdparty -xr!dist -xr!package-lock.json -xr!*.7z -xr!*.svn -piman123
Pause



