/*
 * Copyright (c) 2011, Fritz Feuerbacher.
 */
package com.feuersoft.imanager.ui;

/**
 * @author Fritz Feuerbacher
 */
public class DisplayTextJPanel extends javax.swing.JPanel {

    public static final String TITLE_NAME = "Display Report";
    /** Creates new form DisplayTextJPanel
     * @param text - The text to display.
     */
    public DisplayTextJPanel(String text)
    {
      initComponents();
      jTextAreaDisplayText.setEditable(false);
      jTextAreaDisplayText.setText(text);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jScrollPane1 = new javax.swing.JScrollPane();
      jTextAreaDisplayText = new javax.swing.JTextArea();

      jTextAreaDisplayText.setColumns(20);
      jTextAreaDisplayText.setRows(5);
      jScrollPane1.setViewportView(jTextAreaDisplayText);

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
      this.setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE)
      );
   }// </editor-fold>//GEN-END:initComponents


   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JTextArea jTextAreaDisplayText;
   // End of variables declaration//GEN-END:variables

}
