/*
 * Copyright (c) 2011, Fritz Feuerbacher.
 */
package com.feuersoft.imanager.ui;

import javax.swing.SpinnerNumberModel;

/**
 * @author Fritz Feuerbacher
 */
public class EditProxyJPanel 
   extends javax.swing.JPanel
{
    public static final String TITLE_NAME = "Configure Proxy";

    /** Creates new form EditProxyJPanel
     * @param ipAddress - The proxy IP address.
     * @param port -  The proxy port.
     * @param useProxy - Should we use the proxy?
     */
    public EditProxyJPanel(String ipAddress, int port, boolean useProxy)
    {
      initComponents();
      setIpAddressRx(ipAddress);
      jCheckBoxUseProxy.setSelected(useProxy);
      jSpinnerProxyPort.setValue(port);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jCheckBoxUseProxy = new javax.swing.JCheckBox();
      iPAddressInputFieldProxyAddress = new com.feuersoft.imanager.common.IPAddressInputField();
      jLabel1 = new javax.swing.JLabel();
      jSpinnerProxyPort = new javax.swing.JSpinner();
      jLabel2 = new javax.swing.JLabel();

      jCheckBoxUseProxy.setText("Use Proxy");
      jCheckBoxUseProxy.setToolTipText("Select this if your internet connection uses a proxy server");

      jLabel1.setText("Proxy Address");

      jSpinnerProxyPort.setModel(new javax.swing.SpinnerNumberModel(80, 1, 65535, 1));
      jSpinnerProxyPort.setEditor(new javax.swing.JSpinner.NumberEditor(jSpinnerProxyPort, "0"));

      jLabel2.setText("Port");

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
      this.setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                  .addGap(115, 115, 115)
                  .addComponent(jCheckBoxUseProxy))
               .addGroup(layout.createSequentialGroup()
                  .addContainerGap()
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(layout.createSequentialGroup()
                        .addComponent(iPAddressInputFieldProxyAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSpinnerProxyPort, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                     .addComponent(jLabel1))))
            .addContainerGap(10, javax.swing.GroupLayout.PREFERRED_SIZE))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jCheckBoxUseProxy)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                  .addComponent(jSpinnerProxyPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(jLabel2))
               .addGroup(layout.createSequentialGroup()
                  .addComponent(jLabel1)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(iPAddressInputFieldProxyAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );
   }// </editor-fold>//GEN-END:initComponents


   // Variables declaration - do not modify//GEN-BEGIN:variables
   private com.feuersoft.imanager.common.IPAddressInputField iPAddressInputFieldProxyAddress;
   private javax.swing.JCheckBox jCheckBoxUseProxy;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JSpinner jSpinnerProxyPort;
   // End of variables declaration//GEN-END:variables

  public String getIPAddress()
  {
    return iPAddressInputFieldProxyAddress.getIPAddress();
  }

  private void setIpAddressRx(String ipAddressRx)
  {
    this.iPAddressInputFieldProxyAddress.setIPAddress(ipAddressRx);
  }

  public boolean isUseProxy()
  {
    return jCheckBoxUseProxy.isSelected();
  }

  public int getProxyPort()
  {
    return ((SpinnerNumberModel)jSpinnerProxyPort.getModel())
                                     .getNumber().intValue();
  }
}
