/*
 * Copyright (c) 2010, Fritz Feuerbacher.
 */
package com.feuersoft.imanager.ui;

import com.feuersoft.imanager.enums.MarketPosition;
import com.feuersoft.imanager.enums.PriceLevel;
import com.feuersoft.imanager.persistence.HibernateDataManagerDyn;
import com.feuersoft.imanager.persistence.MarketSegment;
import com.feuersoft.imanager.persistence.ProductLine;
import com.feuersoft.imanager.persistence.ProductVendor;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;

/**
 * @author Fritz Feuerbacher
 */
public class EditProductLineJPanel extends javax.swing.JPanel {

    public static final String DISPLAY_NAME = "Edit Product Line";
    private final HibernateDataManagerDyn hdm = new HibernateDataManagerDyn();
    
    /** Creates new form EditProductLineJPanel */
    public EditProductLineJPanel()
    {
      initComponents();
      jXDatePickerLastPhysical.setDate(new Date());
      jXDatePickerPriceEffectiveDate.setDate(new Date());

      for (ProductVendor v : hdm.getAllProductVendors())
      {
        ((DefaultComboBoxModel)jComboBoxPrimaryVendor.getModel()).addElement(v);
      }

      for (MarketPosition p : MarketPosition.values())
      {
        ((DefaultComboBoxModel)jComboBoxMarketPosition.getModel()).addElement(p);
      }
      
      for (MarketSegment s : hdm.getAllMarketSegments())
      {
        ((DefaultComboBoxModel)jComboBoxMarketSegment.getModel()).addElement(s);
      }
      
      for (PriceLevel pl : PriceLevel.values())
      {
        ((DefaultComboBoxModel)jComboBoxSellPriceField.getModel())
                                                   .addElement(pl);
        ((DefaultComboBoxModel)jComboBoxListPriceField.getModel())
                                                   .addElement(pl);        
      }
    }

    public EditProductLineJPanel(ProductLine line)
    {
      this();
      jXDatePickerLastPhysical.setDate(line.getLastPhysicalInventory());
      jXDatePickerPriceEffectiveDate.setDate(line.getPriceEffectiveDate());
      jTextPaneDescription.setText(line.getDescription());
      jTextFieldLineCode.setText(line.getLineCode());
      jTextFieldProductLineName.setText(line.getProductLineName());
      jComboBoxPrimaryVendor.setSelectedItem(line.getVendor());
      jFormattedTextFieldLastYearSales.setValue(line.getLastYearSales());
      jFormattedTextFieldYearToDateSales.setValue(line.getYearToDateSales());
      jComboBoxMarketPosition.setSelectedItem(line.getMarketPosition());
      jComboBoxMarketSegment.setSelectedItem(line.getMarketSegment());
      jComboBoxSellPriceField.setSelectedItem(line.getDefaultPriceLevel());
      jComboBoxListPriceField.setSelectedItem(line.getDefaultListPriceLevel());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jTextFieldProductLineName = new javax.swing.JTextField();
    jTextFieldLineCode = new javax.swing.JTextField();
    jTextFieldLineCode.setDocument(new com.feuersoft.imanager.ui.JTextFieldLimitUpper(3));
    jLabel2 = new javax.swing.JLabel();
    jXDatePickerPriceEffectiveDate = new org.jdesktop.swingx.JXDatePicker();
    jXDatePickerLastPhysical = new org.jdesktop.swingx.JXDatePicker();
    jLabel1 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jComboBoxPrimaryVendor = new javax.swing.JComboBox();
    jLabel6 = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    jTextPaneDescription = new javax.swing.JTextPane();
    jFormattedTextFieldYearToDateSales = new javax.swing.JFormattedTextField();
    jFormattedTextFieldLastYearSales = new javax.swing.JFormattedTextField();
    jLabel4 = new javax.swing.JLabel();
    jComboBoxMarketPosition = new javax.swing.JComboBox();
    jLabel5 = new javax.swing.JLabel();
    jComboBoxMarketSegment = new javax.swing.JComboBox();
    jLabel7 = new javax.swing.JLabel();
    jComboBoxSellPriceField = new javax.swing.JComboBox();
    jLabel21 = new javax.swing.JLabel();
    jComboBoxListPriceField = new javax.swing.JComboBox();

    jTextFieldProductLineName.setBorder(javax.swing.BorderFactory.createTitledBorder("Product Line Name"));

    jTextFieldLineCode.setToolTipText("The product line code is used to reference the product line when working with inventory items");
    jTextFieldLineCode.setBorder(javax.swing.BorderFactory.createTitledBorder("Product Line Code"));

    jLabel2.setText("Description");

    jLabel1.setText("Price Effective");

    jLabel3.setText("Last Physical Inventory");

    jComboBoxPrimaryVendor.setAutoscrolls(true);

    jLabel6.setText("Vendor");

    jScrollPane1.setViewportView(jTextPaneDescription);

    jFormattedTextFieldYearToDateSales.setBorder(javax.swing.BorderFactory.createTitledBorder("Year to Date Sales"));
    jFormattedTextFieldYearToDateSales.setValue(new Double(0.0));

    jFormattedTextFieldLastYearSales.setBorder(javax.swing.BorderFactory.createTitledBorder("Last Year Sales"));
    jFormattedTextFieldLastYearSales.setValue(new Double(0.0));

    jLabel4.setText("Position");

    jLabel5.setText("Market Segment");

    jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel7.setText("Default Sell Price Field");

    jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel21.setText("Default List Price Field");

    jComboBoxListPriceField.setRenderer(new javax.swing.DefaultListCellRenderer() {
      @Override
      public void paint(java.awt.Graphics g) {
        setForeground(java.awt.Color.BLACK);
        super.paint(g);
      }
    });
    jComboBoxListPriceField.setToolTipText("You will usually list price to price \"G\" since it would be the highest.");
    jComboBoxListPriceField.setAutoscrolls(true);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
              .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxMarketPosition, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
              .addComponent(jFormattedTextFieldYearToDateSales, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
              .addComponent(jFormattedTextFieldLastYearSales, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jLabel5))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(jComboBoxPrimaryVendor, javax.swing.GroupLayout.Alignment.TRAILING, 0, 274, Short.MAX_VALUE)
              .addComponent(jLabel6)
              .addComponent(jComboBoxMarketSegment, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
          .addComponent(jTextFieldProductLineName, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel2)
          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
              .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
              .addComponent(jComboBoxListPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addGap(40, 40, 40)
              .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
              .addComponent(jComboBoxSellPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
              .addComponent(jTextFieldLineCode, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addGap(18, 18, 18)
              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jXDatePickerPriceEffectiveDate, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel1))
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel3)
                .addComponent(jXDatePickerLastPhysical, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jTextFieldProductLineName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel1)
          .addComponent(jLabel3))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jXDatePickerPriceEffectiveDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jXDatePickerLastPhysical, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jTextFieldLineCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGap(22, 22, 22)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabel21)
              .addComponent(jComboBoxListPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabel7)
              .addComponent(jComboBoxSellPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(jFormattedTextFieldYearToDateSales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jFormattedTextFieldLastYearSales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel6)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jComboBoxPrimaryVendor, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addGap(12, 12, 12)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel4)
          .addComponent(jComboBoxMarketPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jComboBoxMarketSegment, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel5))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel2)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JComboBox jComboBoxListPriceField;
  private javax.swing.JComboBox jComboBoxMarketPosition;
  private javax.swing.JComboBox jComboBoxMarketSegment;
  private javax.swing.JComboBox jComboBoxPrimaryVendor;
  private javax.swing.JComboBox jComboBoxSellPriceField;
  private javax.swing.JFormattedTextField jFormattedTextFieldLastYearSales;
  private javax.swing.JFormattedTextField jFormattedTextFieldYearToDateSales;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel21;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTextField jTextFieldLineCode;
  private javax.swing.JTextField jTextFieldProductLineName;
  private javax.swing.JTextPane jTextPaneDescription;
  private org.jdesktop.swingx.JXDatePicker jXDatePickerLastPhysical;
  private org.jdesktop.swingx.JXDatePicker jXDatePickerPriceEffectiveDate;
  // End of variables declaration//GEN-END:variables

  public String getDescription()
  {
    return jTextPaneDescription.getText();
  }

  public String getProductLineCode()
  {
    return jTextFieldLineCode.getText().toUpperCase();
  }

  public String getProductLineName()
  {
    return jTextFieldProductLineName.getText();
  }

  public Date getLastPhysical()
  {
    return jXDatePickerLastPhysical.getDate();
  }

  public Date getPriceEffective()
  {
    return jXDatePickerPriceEffectiveDate.getDate();
  }

  public double getLastYearSales()
  {
    return ((Number)jFormattedTextFieldLastYearSales.getValue()).doubleValue();
  }

  public double getYearToDateSales()
  {
    return ((Number)jFormattedTextFieldYearToDateSales.getValue()).doubleValue();
  }

  public ProductVendor getPrimaryProductVendor()
  {
    return (ProductVendor)jComboBoxPrimaryVendor.getSelectedItem();
  }

  public MarketSegment getMarketSegment()
  {
    return (MarketSegment)jComboBoxMarketSegment.getSelectedItem();
  }

  public MarketPosition getMarketPosition()
  {
    return (MarketPosition)jComboBoxMarketPosition.getSelectedItem();
  }
  
  public PriceLevel getSellPriceField()
  {
    return (PriceLevel)jComboBoxSellPriceField.getSelectedItem();
  }
  
  public PriceLevel getListPriceField()
  {
    return (PriceLevel)jComboBoxListPriceField.getSelectedItem();
  }  
}
