/*
 * Copyright (c) 2011, Fritz Feuerbacher.
 */
package com.feuersoft.imanager.ui;

import com.feuersoft.imanager.enums.PaymentTerms;
import com.feuersoft.imanager.persistence.HibernateDataManagerDyn;
import com.feuersoft.imanager.persistence.ProductVendor;
import javax.swing.DefaultComboBoxModel;

/**
 * @author Fritz Feuerbacher
 */
public class EditProductVendorJPanel extends javax.swing.JPanel {

    public static final String DISPLAY_NAME = "Edit Product Vendor";
    private final HibernateDataManagerDyn hdm = new HibernateDataManagerDyn();
    
    /** Creates new form EditProductVendorJPanel */
    public EditProductVendorJPanel()
    {
      initComponents();
      for (PaymentTerms pt : PaymentTerms.values())
      {
        ((DefaultComboBoxModel)jComboBoxPaymentTerms.getModel()).addElement(pt);
      }
    }

    public EditProductVendorJPanel(ProductVendor vendor)
    {
      this();
      jSpinnerDiscountPercent.setValue(vendor.getDiscountPercent());
      jFormattedTextFieldLastYearSales.setValue(vendor.getTotalLastYear());
      jFormattedTextFieldMinimumForDiscount.setValue(vendor.getMinimumForDiscount());
      jFormattedTextFieldMinimumForShipping.setValue(vendor.getMinimumForShipping());
      jFormattedTextFieldYearToDateSales.setValue(vendor.getTotalThisYear());
      jTextPaneDescription.setText(vendor.getDescription());
      jTextFieldAccountNumber.setText(vendor.getAccountNumber());
      jTextFieldAddress.setText(vendor.getStreetAddress());
      jTextFieldCity.setText(vendor.getCity());
      jTextFieldContactEmail.setText(vendor.getContactEmail());
      jTextFieldContactName.setText(vendor.getContactName());
      jTextFieldCountry.setText(vendor.getCountry());
      jFormattedTextFieldFax.setValue(vendor.getFaxNumber());
      jComboBoxPaymentTerms.setSelectedItem(vendor.getPaymentTerms());
      jFormattedTextFieldPhone.setValue(vendor.getPhoneNumber());
      jTextFieldProductVendorName.setText(vendor.getProductVendorName());
      jTextFieldState.setText(vendor.getStateOrProvince());
      jTextFieldZip.setText(vendor.getZipCode());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jTextFieldProductVendorName = new javax.swing.JTextField();
    jLabel2 = new javax.swing.JLabel();
    jTextFieldAddress = new javax.swing.JTextField();
    jTextFieldCity = new javax.swing.JTextField();
    jTextFieldState = new javax.swing.JTextField();
    jTextFieldZip = new javax.swing.JTextField();
    jTextFieldCountry = new javax.swing.JTextField();
    jTextFieldContactName = new javax.swing.JTextField();
    jTextFieldAccountNumber = new javax.swing.JTextField();
    jTextFieldContactEmail = new javax.swing.JTextField();
    jLabel6 = new javax.swing.JLabel();
    jSpinnerDiscountPercent = new javax.swing.JSpinner(new javax.swing.SpinnerNumberModel(0,0,1,.005));
    jSpinnerDiscountPercent.setEditor(new javax.swing.JSpinner.NumberEditor(jSpinnerDiscountPercent,"0.0%"));
    jScrollPane1 = new javax.swing.JScrollPane();
    jTextPaneDescription = new javax.swing.JTextPane();
    jFormattedTextFieldMinimumForDiscount = new javax.swing.JFormattedTextField();
    jFormattedTextFieldYearToDateSales = new javax.swing.JFormattedTextField();
    jFormattedTextFieldLastYearSales = new javax.swing.JFormattedTextField();
    javax.swing.text.MaskFormatter mask = null;
    try {
      mask = new javax.swing.text.MaskFormatter("(###) ###-####");
      mask.setPlaceholderCharacter('_');
    } catch (java.text.ParseException pe){}
    jFormattedTextFieldPhone = new javax.swing.JFormattedTextField(mask);
    javax.swing.text.MaskFormatter mask2 = null;
    try {
      mask2 = new javax.swing.text.MaskFormatter("(###) ###-####");
      mask2.setPlaceholderCharacter('_');
    } catch (java.text.ParseException pe){}
    jFormattedTextFieldFax = new javax.swing.JFormattedTextField(mask2);
    jLabel7 = new javax.swing.JLabel();
    jComboBoxPaymentTerms = new javax.swing.JComboBox();
    jFormattedTextFieldMinimumForShipping = new javax.swing.JFormattedTextField();

    jTextFieldProductVendorName.setBorder(javax.swing.BorderFactory.createTitledBorder("Product Vendor Name"));

    jLabel2.setText("Description");

    jTextFieldAddress.setBorder(javax.swing.BorderFactory.createTitledBorder("Address"));

    jTextFieldCity.setBorder(javax.swing.BorderFactory.createTitledBorder("City"));

    jTextFieldState.setBorder(javax.swing.BorderFactory.createTitledBorder("State"));

    jTextFieldZip.setBorder(javax.swing.BorderFactory.createTitledBorder("Zip"));

    jTextFieldCountry.setBorder(javax.swing.BorderFactory.createTitledBorder("Country"));

    jTextFieldContactName.setBorder(javax.swing.BorderFactory.createTitledBorder("Contact Name"));

    jTextFieldAccountNumber.setBorder(javax.swing.BorderFactory.createTitledBorder("Account Number"));

    jTextFieldContactEmail.setBorder(javax.swing.BorderFactory.createTitledBorder("Contact Email"));

    jLabel6.setText("Discount");

    jScrollPane1.setViewportView(jTextPaneDescription);

    jFormattedTextFieldMinimumForDiscount.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Minimum for Discount"), "Minimum for Discount"));
    jFormattedTextFieldMinimumForDiscount.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
    jFormattedTextFieldMinimumForDiscount.setValue(new Double(0.0));

    jFormattedTextFieldYearToDateSales.setBorder(javax.swing.BorderFactory.createTitledBorder("Year to Date Sales"));
    jFormattedTextFieldYearToDateSales.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
    jFormattedTextFieldYearToDateSales.setValue(new Double(0.0));

    jFormattedTextFieldLastYearSales.setBorder(javax.swing.BorderFactory.createTitledBorder("Last Year Sales"));
    jFormattedTextFieldLastYearSales.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
    jFormattedTextFieldLastYearSales.setValue(new Double(0.0));

    jFormattedTextFieldPhone.setBorder(javax.swing.BorderFactory.createTitledBorder("Phone Number"));

    jFormattedTextFieldFax.setBorder(javax.swing.BorderFactory.createTitledBorder("Fax Number"));

    jLabel7.setText("Payment Terms");

    jComboBoxPaymentTerms.setRenderer(new javax.swing.DefaultListCellRenderer() {
      @Override
      public void paint(java.awt.Graphics g) {
        setForeground(java.awt.Color.BLACK);
        super.paint(g);
      }
    });
    jComboBoxPaymentTerms.setAutoscrolls(true);

    jFormattedTextFieldMinimumForShipping.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Minimum for Shipping"), "Minimum for Shipping"));
    jFormattedTextFieldMinimumForShipping.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
    jFormattedTextFieldMinimumForShipping.setValue(new Double(0.0));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(19, 19, 19)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jTextFieldAccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jFormattedTextFieldYearToDateSales, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jComboBoxPaymentTerms, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addComponent(jLabel6)
                    .addGap(18, 18, 18))
                  .addComponent(jSpinnerDiscountPercent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
              .addComponent(jFormattedTextFieldLastYearSales, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jFormattedTextFieldMinimumForShipping, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jFormattedTextFieldMinimumForDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
          .addComponent(jLabel2)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(jTextFieldCountry)
              .addComponent(jTextFieldCity, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(jFormattedTextFieldPhone)
              .addComponent(jTextFieldState, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addGroup(layout.createSequentialGroup()
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jFormattedTextFieldFax, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jTextFieldZip))))
          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
            .addComponent(jTextFieldProductVendorName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)
            .addComponent(jTextFieldContactEmail, javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextFieldContactName, javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextFieldAddress, javax.swing.GroupLayout.Alignment.LEADING))
          .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(27, 27, 27)
        .addComponent(jTextFieldProductVendorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jTextFieldAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jTextFieldCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jTextFieldZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jTextFieldState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jTextFieldCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jFormattedTextFieldPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jFormattedTextFieldFax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jTextFieldContactName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jTextFieldContactEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(26, 26, 26)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel7)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jTextFieldAccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jComboBoxPaymentTerms, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                  .addComponent(jSpinnerDiscountPercent, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(jFormattedTextFieldMinimumForDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jFormattedTextFieldYearToDateSales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jFormattedTextFieldLastYearSales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jFormattedTextFieldMinimumForShipping, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel2)))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JComboBox jComboBoxPaymentTerms;
  private javax.swing.JFormattedTextField jFormattedTextFieldFax;
  private javax.swing.JFormattedTextField jFormattedTextFieldLastYearSales;
  private javax.swing.JFormattedTextField jFormattedTextFieldMinimumForDiscount;
  private javax.swing.JFormattedTextField jFormattedTextFieldMinimumForShipping;
  private javax.swing.JFormattedTextField jFormattedTextFieldPhone;
  private javax.swing.JFormattedTextField jFormattedTextFieldYearToDateSales;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JSpinner jSpinnerDiscountPercent;
  private javax.swing.JTextField jTextFieldAccountNumber;
  private javax.swing.JTextField jTextFieldAddress;
  private javax.swing.JTextField jTextFieldCity;
  private javax.swing.JTextField jTextFieldContactEmail;
  private javax.swing.JTextField jTextFieldContactName;
  private javax.swing.JTextField jTextFieldCountry;
  private javax.swing.JTextField jTextFieldProductVendorName;
  private javax.swing.JTextField jTextFieldState;
  private javax.swing.JTextField jTextFieldZip;
  private javax.swing.JTextPane jTextPaneDescription;
  // End of variables declaration//GEN-END:variables

  public String getDescription()
  {
    return jTextPaneDescription.getText();
  }

  public Double getDiscountPercent()
  {
    return ((Double)jSpinnerDiscountPercent.getValue());
  }

  public double getLastYearsSales()
  {
    return ((Number)jFormattedTextFieldLastYearSales.getValue()).doubleValue();
  }

  public double getMinimumForDiscount()
  {
     return ((Number)jFormattedTextFieldMinimumForDiscount.getValue()).doubleValue();
  }
  
  public double getMinimumForShipping()
  {
     return ((Number)jFormattedTextFieldMinimumForShipping.getValue()).doubleValue();
  }

  public double getYearToDateSales()
  {
    return ((Number)jFormattedTextFieldYearToDateSales.getValue()).doubleValue();
  }

  public String getAccountNumber()
  {
    return jTextFieldAccountNumber.getText();
  }

  public String getVendorName()
  {
    return jTextFieldProductVendorName.getText();
  }

  public String getAddress()
  {
    return jTextFieldAddress.getText();
  }

  public String getCity()
  {
    return jTextFieldCity.getText();
  }

  public String getContactEmail()
  {
    return jTextFieldContactEmail.getText();
  }

  public String getContactName()
  {
    return jTextFieldContactName.getText();
  }

  public String getCountry()
  {
    return jTextFieldCountry.getText();
  }

  public String getFaxNumber()
  {
    return (String)jFormattedTextFieldFax.getValue();
  }

  public PaymentTerms getPaymentTerms()
  {
    return (PaymentTerms)jComboBoxPaymentTerms.getSelectedItem();
  }

  public String getPhoneNumber()
  {
    return (String)jFormattedTextFieldPhone.getValue();
  }

  public String getState()
  {
    return jTextFieldState.getText();
  }

  public String getZip()
  {
    return jTextFieldZip.getText();
  }
}
