/*
 * Copyright (c) 2011, Fritz Feuerbacher.
 */
package com.feuersoft.imanager.ui;

/**
 * @author Fritz Feuerbacher
 */
public class EditUnitOfMeasureJPanel extends javax.swing.JPanel {

    public static final String DISPLAY_NAME = "Edit Unit of Measure";
    /** Creates new form EditUnitOfMeasureJPanel */
    public EditUnitOfMeasureJPanel() {
        initComponents();
    }

    public EditUnitOfMeasureJPanel(String unitOfMeasureName,
                                   String umAbbreviation,
                                   String umDescription)
    {
      this();
      jTextFieldUnitOfMeasureName.setText(unitOfMeasureName);
      jTextFieldUnitOfMeasureAbbreviation.setText(umAbbreviation);
      jTextPaneDescription.setText(umDescription);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jTextFieldUnitOfMeasureName = new javax.swing.JTextField();
      jTextFieldUnitOfMeasureAbbreviation = new javax.swing.JTextField();
      jScrollPane1 = new javax.swing.JScrollPane();
      jTextPaneDescription = new javax.swing.JTextPane();
      jLabel1 = new javax.swing.JLabel();

      jTextFieldUnitOfMeasureName.setToolTipText("Enter name of unit of measure.  Example: Each, Pound, Carton, Pallet, Foot, Yard, Quart, Gallon, etc");
      jTextFieldUnitOfMeasureName.setBorder(javax.swing.BorderFactory.createTitledBorder("Unit of Measure Name"));

      jTextFieldUnitOfMeasureAbbreviation.setToolTipText("Enter the abbreviated name of unit of measure.  Example: each, lbs, ca., pa., ft, yd, qt, gal, etc");
      jTextFieldUnitOfMeasureAbbreviation.setBorder(javax.swing.BorderFactory.createTitledBorder("Unit of Measure Abbreviation"));

      jTextPaneDescription.setToolTipText("Enter a detailed description of the unit of measure.");
      jScrollPane1.setViewportView(jTextPaneDescription);

      jLabel1.setText("Unit of Measure Description");

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
      this.setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jLabel1)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                  .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jTextFieldUnitOfMeasureName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                  .addComponent(jTextFieldUnitOfMeasureAbbreviation, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jTextFieldUnitOfMeasureName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jTextFieldUnitOfMeasureAbbreviation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
            .addComponent(jLabel1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(22, 22, 22))
      );
   }// </editor-fold>//GEN-END:initComponents


   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JLabel jLabel1;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JTextField jTextFieldUnitOfMeasureAbbreviation;
   private javax.swing.JTextField jTextFieldUnitOfMeasureName;
   private javax.swing.JTextPane jTextPaneDescription;
   // End of variables declaration//GEN-END:variables

  public String getUnitOfMeasureName()
  {
    return jTextFieldUnitOfMeasureName.getText();
  }

  public String getUnitOfMeasureAbbr()
  {
    return jTextFieldUnitOfMeasureAbbreviation.getText();
  }

  public String getUnitOfMeasureDescription()
  {
    return jTextPaneDescription.getText();
  }
}
