/*
 * Copyright (c) 2011, Fritz Feuerbacher.
 */
package com.feuersoft.imanager.ui;

import com.feuersoft.imanager.enums.Size;
import com.feuersoft.imanager.persistence.MarketSegment;
import javax.swing.DefaultComboBoxModel;

/**
 * @author Fritz Feuerbacher
 */
public class EditMarketSegmentJPanel extends javax.swing.JPanel {

    public static final String DISPLAY_NAME = "Edit Market Segment";

    /** Creates new form EditMarketSegmentJPanel */
    public EditMarketSegmentJPanel()
    {
      initComponents();
      for (Size s : Size.values())
      {
        ((DefaultComboBoxModel)jComboBoxSegmentSize.getModel()).addElement(s);
      }
    }

    public EditMarketSegmentJPanel(MarketSegment segment)
    {
      this();
      jComboBoxSegmentSize.setSelectedItem(segment.getSegmentSize());
      jTextFieldMarketSegmentName.setText(segment.getName());
      jTextPaneMarketSegmentDescription.setText(segment.getDescription());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jTextFieldMarketSegmentName = new javax.swing.JTextField();
      jLabel1 = new javax.swing.JLabel();
      jScrollPane1 = new javax.swing.JScrollPane();
      jTextPaneMarketSegmentDescription = new javax.swing.JTextPane();
      jLabel2 = new javax.swing.JLabel();
      jComboBoxSegmentSize = new javax.swing.JComboBox();

      jTextFieldMarketSegmentName.setToolTipText("Enter name of market segment.  E.g. Undercar, Underhood, Heavy Duty, etc.");
      jTextFieldMarketSegmentName.setBorder(javax.swing.BorderFactory.createTitledBorder("Market Segment Name"));

      jLabel1.setText("Market Segment Description");

      jTextPaneMarketSegmentDescription.setToolTipText("Enter a detailed description of the market segment.");
      jScrollPane1.setViewportView(jTextPaneMarketSegmentDescription);

      jLabel2.setText("Segment Size");

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
      this.setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jLabel1)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                  .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jTextFieldMarketSegmentName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                  .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                     .addComponent(jLabel2)
                     .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                     .addComponent(jComboBoxSegmentSize, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jTextFieldMarketSegmentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel2)
               .addComponent(jComboBoxSegmentSize, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jLabel1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );
   }// </editor-fold>//GEN-END:initComponents


   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JComboBox jComboBoxSegmentSize;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JTextField jTextFieldMarketSegmentName;
   private javax.swing.JTextPane jTextPaneMarketSegmentDescription;
   // End of variables declaration//GEN-END:variables


  public String getSegmentDescription()
  {
    return jTextPaneMarketSegmentDescription.getText();
  }

  public String getSegmentName()
  {
    return jTextFieldMarketSegmentName.getText();
  }

  public Size getSegmentSize()
  {
    return (Size)jComboBoxSegmentSize.getSelectedItem();
  }
}
