/*
 * Copyright (c) 2011, Fritz Feuerbacher.
 */
package com.feuersoft.imanager.ui;

import com.feuersoft.imanager.enums.PriceLevel;
import com.feuersoft.imanager.persistence.Company;
import javax.swing.DefaultComboBoxModel;
import javax.swing.SpinnerNumberModel;

/**
 * @author Fritz Feuerbacher
 */
public class EditCompanyJPanel 
     extends javax.swing.JPanel
{
    public static final String DISPLAY_NAME = "Edit Company";
    private Company company = null;

    /** Creates new form EditCustomerJPanel */
    public EditCompanyJPanel()
    {
      initComponents();
      for (PriceLevel pl : PriceLevel.values())
      {
        ((DefaultComboBoxModel)jComboBoxListPriceField.getModel())
                                                   .addElement(pl);
        ((DefaultComboBoxModel)jComboBoxSellPriceField.getModel())
                                                   .addElement(pl);
      }
    }

    /** Creates new form EditCustomerJPanel
     * @param company - The company to edit.
     */
    public EditCompanyJPanel(Company company)
    {
      this();
      if (null != company)
      {
        this.company = company;
        jTextFieldAddress.setText(company.getStreetAddress());
        jTextFieldCity.setText(company.getCity());
        jTextFieldContactEmail.setText(company.getContactEmail());
        jTextFieldContactName.setText(company.getContactName());
        jTextFieldCountry.setText(company.getCountry());
        jFormattedTextFieldFax.setValue(company.getFaxNumber());
        jFormattedTextFieldPhone.setValue(company.getPhoneNumber());
        jTextFieldCompanyName.setText(company.getCompanyName());
        jTextFieldState.setText(company.getStateOrProvince());
        jTextFieldZip.setText(company.getZipCode());
        jComboBoxListPriceField.setSelectedItem(company.getListPriceField());
        jComboBoxSellPriceField.setSelectedItem(company.getDefaultSellPriceField());
        jSpinnerNextInvoiceNumber.setValue(company.getNextInvoiceNumber());
        jSpinnerNextPONumber.setValue(company.getNextPONumber());
      }
      
      // Decided I am going to use the DB id for
      // the invoice and PO numbers.  These numbers
      // are truly uniqe and point directly to the
      // database record.
      jLabelNextInvoiceNumber.setVisible(false);
      jSpinnerNextInvoiceNumber.setVisible(false);
      jLabelNextPurchaseOrderNumber.setVisible(false);
      jSpinnerNextPONumber.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jTextFieldCompanyName = new javax.swing.JTextField();
    jTextFieldAddress = new javax.swing.JTextField();
    jTextFieldCity = new javax.swing.JTextField();
    jTextFieldState = new javax.swing.JTextField();
    jTextFieldZip = new javax.swing.JTextField();
    jTextFieldCountry = new javax.swing.JTextField();
    jTextFieldContactName = new javax.swing.JTextField();
    jTextFieldContactEmail = new javax.swing.JTextField();
    javax.swing.text.MaskFormatter mask = null;
    try {
      mask = new javax.swing.text.MaskFormatter("(###) ###-####");
      mask.setPlaceholderCharacter('_');
    } catch (java.text.ParseException pe){}
    jFormattedTextFieldPhone = new javax.swing.JFormattedTextField(mask);
    javax.swing.text.MaskFormatter mask2 = null;
    try {
      mask2 = new javax.swing.text.MaskFormatter("(###) ###-####");
      mask2.setPlaceholderCharacter('_');
    } catch (java.text.ParseException pe){}
    jFormattedTextFieldFax = new javax.swing.JFormattedTextField(mask2);
    jLabelDefaultListPrice = new javax.swing.JLabel();
    jLabelDefaultListPrice.setVisible(false);
    jComboBoxListPriceField = new javax.swing.JComboBox();
    jComboBoxListPriceField.setVisible(false);
    jSpinnerNextInvoiceNumber = new javax.swing.JSpinner();
    jLabelNextInvoiceNumber = new javax.swing.JLabel();
    jLabelNextPurchaseOrderNumber = new javax.swing.JLabel();
    jSpinnerNextPONumber = new javax.swing.JSpinner();
    jLabelDefaultSellPrice = new javax.swing.JLabel();
    jLabelDefaultSellPrice.setVisible(false);
    jComboBoxSellPriceField = new javax.swing.JComboBox();
    jComboBoxSellPriceField.setVisible(false);

    jTextFieldCompanyName.setBorder(javax.swing.BorderFactory.createTitledBorder("Company Name"));

    jTextFieldAddress.setBorder(javax.swing.BorderFactory.createTitledBorder("Address"));

    jTextFieldCity.setBorder(javax.swing.BorderFactory.createTitledBorder("City"));

    jTextFieldState.setBorder(javax.swing.BorderFactory.createTitledBorder("State"));

    jTextFieldZip.setBorder(javax.swing.BorderFactory.createTitledBorder("Zip"));

    jTextFieldCountry.setBorder(javax.swing.BorderFactory.createTitledBorder("Country"));

    jTextFieldContactName.setBorder(javax.swing.BorderFactory.createTitledBorder("Contact Name"));

    jTextFieldContactEmail.setBorder(javax.swing.BorderFactory.createTitledBorder("Contact Email"));

    jFormattedTextFieldPhone.setBorder(javax.swing.BorderFactory.createTitledBorder("Phone Number"));

    jFormattedTextFieldFax.setBorder(javax.swing.BorderFactory.createTitledBorder("Fax Number"));

    jLabelDefaultListPrice.setText("List Price Field");

    jComboBoxListPriceField.setRenderer(new javax.swing.DefaultListCellRenderer() {
      @Override
      public void paint(java.awt.Graphics g) {
        setForeground(java.awt.Color.BLACK);
        super.paint(g);
      }
    });
    jComboBoxListPriceField.setToolTipText("You will usually list price to price \"G\" since it would be the highest.");
    jComboBoxListPriceField.setAutoscrolls(true);

    jSpinnerNextInvoiceNumber.setModel(new javax.swing.SpinnerNumberModel(1L, 1L, null, 1L));
    jSpinnerNextInvoiceNumber.setEnabled(false);
    jSpinnerNextInvoiceNumber.setEditor(new javax.swing.JSpinner.NumberEditor(jSpinnerNextInvoiceNumber, "0"));

    jLabelNextInvoiceNumber.setText("Next Invoice Number");
    jLabelNextInvoiceNumber.setEnabled(false);

    jLabelNextPurchaseOrderNumber.setText("Next Purchase Order Number");
    jLabelNextPurchaseOrderNumber.setEnabled(false);

    jSpinnerNextPONumber.setModel(new javax.swing.SpinnerNumberModel(1L, 1L, null, 1L));
    jSpinnerNextPONumber.setEnabled(false);
    jSpinnerNextPONumber.setEditor(new javax.swing.JSpinner.NumberEditor(jSpinnerNextPONumber, "0"));

    jLabelDefaultSellPrice.setText("Default Sell Price");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelNextInvoiceNumber)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSpinnerNextInvoiceNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelDefaultSellPrice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxSellPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(jLabelDefaultListPrice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxListPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabelNextPurchaseOrderNumber)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSpinnerNextPONumber, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
            .addGroup(layout.createSequentialGroup()
              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(jTextFieldCountry)
                .addComponent(jTextFieldCity, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE))
              .addGap(18, 18, 18)
              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(jFormattedTextFieldPhone)
                .addComponent(jTextFieldState, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))
              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addGroup(layout.createSequentialGroup()
                  .addGap(12, 12, 12)
                  .addComponent(jTextFieldZip, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createSequentialGroup()
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addComponent(jFormattedTextFieldFax))))
            .addComponent(jTextFieldAddress)
            .addComponent(jTextFieldContactName)
            .addComponent(jTextFieldContactEmail)
            .addComponent(jTextFieldCompanyName)))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jTextFieldCompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jTextFieldAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jTextFieldCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jTextFieldZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jTextFieldState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jTextFieldCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(jFormattedTextFieldPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jFormattedTextFieldFax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jTextFieldContactName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jTextFieldContactEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabelDefaultListPrice)
          .addComponent(jComboBoxListPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabelDefaultSellPrice)
          .addComponent(jComboBoxSellPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabelNextInvoiceNumber)
          .addComponent(jSpinnerNextInvoiceNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jSpinnerNextPONumber, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabelNextPurchaseOrderNumber))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JComboBox jComboBoxListPriceField;
  private javax.swing.JComboBox jComboBoxSellPriceField;
  private javax.swing.JFormattedTextField jFormattedTextFieldFax;
  private javax.swing.JFormattedTextField jFormattedTextFieldPhone;
  private javax.swing.JLabel jLabelDefaultListPrice;
  private javax.swing.JLabel jLabelDefaultSellPrice;
  private javax.swing.JLabel jLabelNextInvoiceNumber;
  private javax.swing.JLabel jLabelNextPurchaseOrderNumber;
  private javax.swing.JSpinner jSpinnerNextInvoiceNumber;
  private javax.swing.JSpinner jSpinnerNextPONumber;
  private javax.swing.JTextField jTextFieldAddress;
  private javax.swing.JTextField jTextFieldCity;
  private javax.swing.JTextField jTextFieldCompanyName;
  private javax.swing.JTextField jTextFieldContactEmail;
  private javax.swing.JTextField jTextFieldContactName;
  private javax.swing.JTextField jTextFieldCountry;
  private javax.swing.JTextField jTextFieldState;
  private javax.swing.JTextField jTextFieldZip;
  // End of variables declaration//GEN-END:variables

  public String getCompanyName()
  {
    return jTextFieldCompanyName.getText();
  }

  public String getAddress()
  {
    return jTextFieldAddress.getText();
  }

  public String getCity()
  {
    return jTextFieldCity.getText();
  }

  public String getContactEmail()
  {
    return jTextFieldContactEmail.getText();
  }

  public String getContactName()
  {
    return jTextFieldContactName.getText();
  }

  public String getCountry()
  {
    return jTextFieldCountry.getText();
  }

  public String getFaxNumber()
  {
    String faxNumber = (String)jFormattedTextFieldFax.getValue();
    
    if (null == faxNumber)
    {
      faxNumber = "";
    }
    return faxNumber;    
  }

  public String getPhoneNumber()
  {
    String phoneNumber = (String)jFormattedTextFieldPhone.getValue();
    
    if (null == phoneNumber)
    {
      phoneNumber = "";
    }
    return phoneNumber;
  }

  public String getState()
  {
    return jTextFieldState.getText();
  }

  public String getZip()
  {
    return jTextFieldZip.getText();
  }

  public PriceLevel getListPriceField()
  {
    return (PriceLevel)jComboBoxListPriceField.getSelectedItem();
  }

  public PriceLevel getSellPriceField()
  {
    return (PriceLevel)jComboBoxSellPriceField.getSelectedItem();
  }

  public long getNextInvoiceNumber()
  {
    return ((SpinnerNumberModel)jSpinnerNextInvoiceNumber.getModel())
                                     .getNumber().longValue();
  }

  public long getNextPONumber()
  {
    return ((SpinnerNumberModel)jSpinnerNextPONumber.getModel())
                                     .getNumber().longValue();
  }
}
