/*
/*
 * Copyright (c) 2011, Fritz Feuerbacher.
 */
package com.feuersoft.imanager.ui;

/**
 * @author Fritz Feuerbacher
 */
public class ItemMemoJPanel 
   extends javax.swing.JPanel
{
    public static final String TITLE_NAME = "Edit Notes";
    /** Creates new form ItemMemoJPanel
     * @param memo - memo to display.
     * @param editable - True if can edit, false for read-only.
     */
    public ItemMemoJPanel(String memo, boolean editable)
    {
      initComponents();
      jTextPaneDescription.setText(memo);
      jTextPaneDescription.setEditable(editable);
      jTextPaneDescription.setEnabled(editable);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jScrollPane1 = new javax.swing.JScrollPane();
    jTextPaneDescription = new javax.swing.JTextPane();
    jLabel1 = new javax.swing.JLabel();

    jTextPaneDescription.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
    jScrollPane1.setViewportView(jTextPaneDescription);

    jLabel1.setText("Item Notes");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 581, Short.MAX_VALUE)
          .addComponent(jLabel1))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(11, 11, 11)
        .addComponent(jLabel1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
        .addContainerGap())
    );
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel jLabel1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTextPane jTextPaneDescription;
  // End of variables declaration//GEN-END:variables

  public String getMemo()
  {
    return jTextPaneDescription.getText();
  }
}
