/*
 * Copyright (c) 2011, Fritz Feuerbacher.
 */
package com.feuersoft.imanager.ui;

/**
 * @author Fritz Feuerbacher
 */
public class LookupItemJPanel extends javax.swing.JPanel {

    public static final String DISPLAY_TITLE = "Lookup Inventory Item";

    /** Creates new form LookupItemJPanel */
    public LookupItemJPanel() {
        initComponents();
    }

    /** Creates new form LookupItemJPanel
     * @param border - string to display in the border.
     */
    public LookupItemJPanel(String border)
    {
      this();
      jTextFieldItemNumber.
             setBorder(javax.swing.BorderFactory.createTitledBorder(border));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jTextFieldItemNumber = new UpperCaseJTextField();

      jTextFieldItemNumber.setToolTipText("");
      jTextFieldItemNumber.setBorder(javax.swing.BorderFactory.createTitledBorder("Enter Item Number"));

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
      this.setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jTextFieldItemNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jTextFieldItemNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );
   }// </editor-fold>//GEN-END:initComponents


   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JTextField jTextFieldItemNumber;
   // End of variables declaration//GEN-END:variables

  public String getItemNumber()
  {
    return jTextFieldItemNumber.getText();
  }
}
