/*
 * Copyright (c) 2011, Fritz Feuerbacher.
 */
package com.feuersoft.imanager.ui;

import com.feuersoft.imanager.common.Utils;
import com.feuersoft.imanager.persistence.HibernateDataManagerDyn;
import com.feuersoft.imanager.persistence.ProductLine;
import java.util.Collections;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * @author Fritz Feuerbacher
 */
public class LookupItemLikeJPanel extends javax.swing.JPanel {

    private static final Logger LOG =
            LoggerFactory.getLogger(LookupItemLikeJPanel.class);  
    public static final String DISPLAY_NAME = "Search Inventory Item";
    private final HibernateDataManagerDyn hdm = new HibernateDataManagerDyn();
    private final ProductLine allProductLines = new ProductLine(Utils.ALL_LINES_MSG);

    /** Creates new form LookupItemJPanel */
    public LookupItemLikeJPanel()
    {
      initComponents();

      List<ProductLine> plList = hdm.getAllProductLines();
      Collections.sort(plList);
      for (ProductLine l : plList)
      {
        ((DefaultComboBoxModel)jComboBoxProductLine.getModel())
                                                .addElement(l);
      }
      ((DefaultComboBoxModel)jComboBoxProductLine.getModel())
                                 .addElement(allProductLines);
      jComboBoxProductLine.setSelectedItem(allProductLines);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jTextFieldItemSearchText = new UpperCaseJTextField();
    jLabelSelectProductLine = new javax.swing.JLabel();
    jComboBoxProductLine = new javax.swing.JComboBox();
    jTextFieldCode1 = new javax.swing.JTextField();
    jTextFieldCode2 = new javax.swing.JTextField();
    jTextFieldCode3 = new javax.swing.JTextField();

    jTextFieldItemSearchText.setToolTipText("");
    jTextFieldItemSearchText.setBorder(javax.swing.BorderFactory.createTitledBorder("Enter Item Text"));

    jLabelSelectProductLine.setText("Select product line");

    jComboBoxProductLine.setAutoscrolls(true);

    jTextFieldCode1.setDocument(new com.feuersoft.imanager.ui.JTextFieldLimitUpper(1, true));
    jTextFieldCode1.setToolTipText("Codes are used to custom mark items for running reports");
    jTextFieldCode1.setBorder(javax.swing.BorderFactory.createTitledBorder("Code 1"));

    jTextFieldCode2.setDocument(new com.feuersoft.imanager.ui.JTextFieldLimitUpper(1, true));
    jTextFieldCode2.setToolTipText("Codes are used to custom mark items for running reports");
    jTextFieldCode2.setBorder(javax.swing.BorderFactory.createTitledBorder("Code 2"));

    jTextFieldCode3.setDocument(new com.feuersoft.imanager.ui.JTextFieldLimitUpper(1, true));
    jTextFieldCode3.setToolTipText("Codes are used to custom mark items for running reports");
    jTextFieldCode3.setBorder(javax.swing.BorderFactory.createTitledBorder("Code 3"));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jComboBoxProductLine, 0, 309, Short.MAX_VALUE)
          .addComponent(jTextFieldItemSearchText, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabelSelectProductLine)
              .addGroup(layout.createSequentialGroup()
                .addComponent(jTextFieldCode1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldCode2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldCode3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGap(0, 0, Short.MAX_VALUE)))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabelSelectProductLine)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jComboBoxProductLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jTextFieldItemSearchText, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jTextFieldCode1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jTextFieldCode2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jTextFieldCode3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JComboBox jComboBoxProductLine;
  private javax.swing.JLabel jLabelSelectProductLine;
  private javax.swing.JTextField jTextFieldCode1;
  private javax.swing.JTextField jTextFieldCode2;
  private javax.swing.JTextField jTextFieldCode3;
  private javax.swing.JTextField jTextFieldItemSearchText;
  // End of variables declaration//GEN-END:variables

  public String getItemSearchText()
  {
    return jTextFieldItemSearchText.getText();
  }
  
  public String getCode1()
  {
    return jTextFieldCode1.getText();
  }
  
  public String getCode2()
  {
    return jTextFieldCode2.getText();
  }

  public String getCode3()
  {
    return jTextFieldCode3.getText();
  }
  
  public String[] getCodes()
  {
    String[] codes = {null, null, null};
    
    if (!getCode1().isEmpty())
    {
      codes[0] = getCode1();
    }
    if (!getCode2().isEmpty())
    {
      codes[1] = getCode2();
    }
    if (!getCode3().isEmpty())
    {
      codes[2] = getCode3();
    }

    return codes;
  }
  
  public ProductLine getProductLine()
  {
    ProductLine prodLine = (ProductLine)jComboBoxProductLine.getSelectedItem();

    if (prodLine == allProductLines)
    {
      prodLine = null;
    }

    return prodLine;
  }
}
