/*
 * To change this template, choose Tools | Templates
/*
 * Copyright (c) 2011, Fritz Feuerbacher.
 */

package com.feuersoft.imanager.ui;

/**
 * @author Fritz Feuerbacher
 */
public class PromptURLJPanel 
   extends javax.swing.JPanel
{
    public static final String TITLE_NAME = "Enter Item Image URL";

    /** Creates new form PromptURLJPanel */
    public PromptURLJPanel()
    {
      initComponents();
    }

    public PromptURLJPanel(String url)
    {
      initComponents();
      jTextFieldURL.setText(url);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jTextFieldURL = new javax.swing.JTextField();

      jTextFieldURL.setToolTipText("To paste a URL that you copied, click inside the text box and hit the CTRL-V key.");
      jTextFieldURL.setBorder(javax.swing.BorderFactory.createTitledBorder("Item Image URL"));

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
      this.setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jTextFieldURL, javax.swing.GroupLayout.DEFAULT_SIZE, 595, Short.MAX_VALUE)
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jTextFieldURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );
   }// </editor-fold>//GEN-END:initComponents


   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JTextField jTextFieldURL;
   // End of variables declaration//GEN-END:variables

  public String getURL()
  {
    return jTextFieldURL.getText();
  }
}
