/*
 * Copyright (c) 2011, Fritz Feuerbacher.
 */
package com.feuersoft.imanager.ui;

import com.feuersoft.imanager.persistence.HibernateDataManagerDyn;
import com.feuersoft.imanager.persistence.Item;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 * @author Fritz Feuerbacher
 */
public class SearchItemDeleteListJPanel extends javax.swing.JPanel {

    public static final String TITLE_NAME = "Select Item(s) to Delete";
    private final HibernateDataManagerDyn hdm = new HibernateDataManagerDyn();
    
    /** Creates new form SearchItemDeleteListJPanel
     * @param itemList - the list to delete.
     */
    public SearchItemDeleteListJPanel(List<Item> itemList)
    {
      initComponents();
      DefaultListModel listModel =
              (DefaultListModel)jListSearchItemList.getModel();
      Collections.sort(itemList);
      for (Item i : itemList)
      {
        listModel.addElement(i);
      }
      jListSearchItemList.setModel(listModel);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jScrollPane1 = new javax.swing.JScrollPane();
      jListSearchItemList = new javax.swing.JList();
      jLabel1 = new javax.swing.JLabel();
      jButtonDeleteSelectedItems = new javax.swing.JButton();

      jListSearchItemList.setModel(new javax.swing.DefaultListModel());
      jScrollPane1.setViewportView(jListSearchItemList);

      jLabel1.setText("Select multiple items by holding down the Ctrl key");

      jButtonDeleteSelectedItems.setText("Delete Selected Item(s)");
      jButtonDeleteSelectedItems.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonDeleteSelectedItemsActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
      this.setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
               .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jButtonDeleteSelectedItems))
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jButtonDeleteSelectedItems)
            .addContainerGap(21, Short.MAX_VALUE))
      );
   }// </editor-fold>//GEN-END:initComponents

    private void jButtonDeleteSelectedItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteSelectedItemsActionPerformed

      for (Item i : getSelectedItems())
      {
        hdm.removeObjectFromDB(i);
        ((DefaultListModel)jListSearchItemList.getModel()).removeElement(i);
      }
    }//GEN-LAST:event_jButtonDeleteSelectedItemsActionPerformed

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton jButtonDeleteSelectedItems;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JList jListSearchItemList;
   private javax.swing.JScrollPane jScrollPane1;
   // End of variables declaration//GEN-END:variables

  public Item getSelectedItem()
  {
    Item selectedItem = null;

    if (jListSearchItemList.getModel().getSize() > 0)
    {
      selectedItem = (Item)jListSearchItemList.getSelectedValue();
    }
    return selectedItem;
  }

  public List<Item> getSelectedItems()
  {
    List<Item> itemList = new ArrayList<Item>();

    for (Object o : jListSearchItemList.getSelectedValuesList())
    {
       itemList.add((Item)o);
    }
    return itemList;
  }
}
