/*
 * Copyright (c) 2011, Fritz Feuerbacher.
 */
package com.feuersoft.imanager.ui;

import com.feuersoft.imanager.persistence.BinLocation;
import com.feuersoft.imanager.persistence.HibernateDataManagerDyn;
import java.util.Collections;
import java.util.List;
import javax.swing.DefaultComboBoxModel;

/**
 * @author Fritz Feuerbacher
 */
public class SelectBinLocationJPanel extends javax.swing.JPanel {

    public static final String DISPLAY_NAME = "Select Bin Location";
    
    /** Creates new form SelectBinLocationJPanel */
    public SelectBinLocationJPanel() {
        initComponents();
        List<BinLocation> bins = (new HibernateDataManagerDyn()).getAllBinLocations();
        Collections.sort(bins);
        for (BinLocation b : bins)
        {
          ((DefaultComboBoxModel)jComboBoxBinLocations.getModel()).addElement(b);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jComboBoxBinLocations = new javax.swing.JComboBox();

      jComboBoxBinLocations.setAutoscrolls(true);

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
      this.setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGap(26, 26, 26)
            .addComponent(jComboBoxBinLocations, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(30, Short.MAX_VALUE))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGap(22, 22, 22)
            .addComponent(jComboBoxBinLocations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(27, Short.MAX_VALUE))
      );
   }// </editor-fold>//GEN-END:initComponents


   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JComboBox jComboBoxBinLocations;
   // End of variables declaration//GEN-END:variables

  public BinLocation getBinLocation()
  {
    return (BinLocation)jComboBoxBinLocations.getSelectedItem();
  }
}
