/*
 * Copyright (c) 2011, Fritz Feuerbacher.
 */
package com.feuersoft.imanager.ui;

import java.util.Collections;
import java.util.List;
import javax.swing.DefaultComboBoxModel;

/**
 * @author Fritz Feuerbacher
 */
public class SelectObjectJPanel extends javax.swing.JPanel {

    public static final String DISPLAY_TITLE = "Make Selection";

    /** Creates new form SelectObjectJPanel
     *  @param objects - list of objects you want to display.
     * @param toolTip - tooltip to display.  Can be null.
     */
    public SelectObjectJPanel(final List objects, final String toolTip)
    {
      initComponents();
      
      // Sort the objects.  The compare function should be written
      // such that the sort puts the most relevant item at the top.
      Collections.sort(objects);

      for (Object o : objects)
      {
        ((DefaultComboBoxModel)jComboBoxObjects.getModel()).addElement(o);
      }
      
      if (null != toolTip)
      {
        jComboBoxObjects.setToolTipText(toolTip);
      }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jComboBoxObjects = new javax.swing.JComboBox();

      jComboBoxObjects.setAutoscrolls(true);

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
      this.setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jComboBoxObjects, 0, 311, Short.MAX_VALUE)
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jComboBoxObjects, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );
   }// </editor-fold>//GEN-END:initComponents


   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JComboBox jComboBoxObjects;
   // End of variables declaration//GEN-END:variables

  public Object getSelctedObject()
  {
    return jComboBoxObjects.getSelectedItem();
  }
}
