/*
 * Copyright (c) 2018, Fritz Feuerbacher.
 */
package com.feuersoft.imanager.ui;

import com.feuersoft.imanager.persistence.HibernateDataManagerDyn;
import com.feuersoft.imanager.persistence.ProductVendor;
import com.feuersoft.imanager.persistence.PurchaseOrder;
import com.feuersoft.imanager.persistence.Store;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import javax.swing.DefaultComboBoxModel;

/**
 * @author Fritz Feuerbacher
 */
public final class SelectVendorAndPurchaseOrder 
        extends javax.swing.JPanel
{
  public static final String TITLE_NAME = "Select Product Vendor and Purchase Order";
  private transient final HibernateDataManagerDyn hdm = new HibernateDataManagerDyn();

  /**
   * Creates new form SelectVendorAndPurchaseOrder
   */
  public SelectVendorAndPurchaseOrder(final Store store)
  {
    initComponents();
    List<ProductVendor> vendors = hdm.getAllProductVendors();
    Collections.sort(vendors);
    
    for (ProductVendor v : vendors)
    {
      ((DefaultComboBoxModel)jComboBoxProductVendors.getModel()).addElement(v);
    }
    
    List<Store> stores = hdm.getAllStores();
    Collections.sort(stores);
    for (Store s : stores)
    {
      ((DefaultComboBoxModel)jComboBoxStores.getModel()).addElement(s);
    }
    
    if (null != store)
    {
      jComboBoxStores.setSelectedItem(store);
    }    

    if (((DefaultComboBoxModel)jComboBoxProductVendors.getModel()).getSize() > 0)
    {
      ProductVendor pv = (ProductVendor)((DefaultComboBoxModel)jComboBoxProductVendors.getModel()).getElementAt(0);
      ((DefaultComboBoxModel)jComboBoxProductVendors.getModel()).setSelectedItem(pv);
      for (PurchaseOrder po : getPurchaseOrders(pv, store))
      {
        ((DefaultComboBoxModel)jComboBoxPurchaseOrders.getModel()).addElement(po);
      }   
    }    

  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    jComboBoxProductVendors = new javax.swing.JComboBox();
    jLabel2 = new javax.swing.JLabel();
    jComboBoxPurchaseOrders = new javax.swing.JComboBox();
    jLabel3 = new javax.swing.JLabel();
    jComboBoxStores = new javax.swing.JComboBox();

    jLabel1.setText("Product Vendor");

    jComboBoxProductVendors.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        jComboBoxProductVendorsItemStateChanged(evt);
      }
    });

    jLabel2.setText("Purchase Order");

    jLabel3.setText("Store");

    jComboBoxStores.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        jComboBoxStoresItemStateChanged(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(jComboBoxProductVendors, 0, 311, Short.MAX_VALUE)
          .addComponent(jComboBoxPurchaseOrders, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jComboBoxStores, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jComboBoxProductVendors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel3)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jComboBoxStores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel2)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jComboBoxPurchaseOrders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents

  private void jComboBoxProductVendorsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxProductVendorsItemStateChanged
    
    if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED)
    {
      setPurchaseOrders();
    }
  }//GEN-LAST:event_jComboBoxProductVendorsItemStateChanged

  private void jComboBoxStoresItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxStoresItemStateChanged
    
    if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED)
    {
      setPurchaseOrders();
    }
  }//GEN-LAST:event_jComboBoxStoresItemStateChanged


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JComboBox jComboBoxProductVendors;
  private javax.swing.JComboBox jComboBoxPurchaseOrders;
  private javax.swing.JComboBox jComboBoxStores;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  // End of variables declaration//GEN-END:variables

  public ProductVendor getProductVendor()
  {
    return (ProductVendor)jComboBoxProductVendors.getSelectedItem();
  }

  public PurchaseOrder getPurchaseOrder()
  {
    return (PurchaseOrder)jComboBoxPurchaseOrders.getSelectedItem();
  }
  
  public Store getStore()
  {
    return (Store)jComboBoxStores.getSelectedItem();
  }  
  
  public List<PurchaseOrder> getPurchaseOrders(final ProductVendor pv, final Store store)
  {
    List<PurchaseOrder> pos = new ArrayList<>();
    if (null != pv && null != store)
    {
      pos = hdm.getPurchaseOrderByVendorStore(pv, store);
      Collections.sort(pos);
    }
    return pos;
  }
 
  public void setPurchaseOrders()
  {
    ((DefaultComboBoxModel)jComboBoxPurchaseOrders.getModel()).removeAllElements();    
    ProductVendor pv = getProductVendor();
    Store store = getStore();
    
    for (PurchaseOrder po : getPurchaseOrders(pv, store))
    {
      ((DefaultComboBoxModel)jComboBoxPurchaseOrders.getModel()).addElement(po);
    }
  }
}
