/*
 * Copyright (c) 2018, Fritz Feuerbacher.
 */
package com.feuersoft.imanager.ui;

import com.feuersoft.imanager.common.Utils;
import com.feuersoft.imanager.persistence.HibernateDataManagerDyn;
import com.feuersoft.imanager.persistence.ProductVendor;
import com.feuersoft.imanager.persistence.Store;
import java.util.Collections;
import java.util.List;
import javax.swing.DefaultComboBoxModel;

/**
 * @author Fritz Feuerbacher
 */
public class SelectVendorAndStoreJPanel 
        extends javax.swing.JPanel 
{
  public static final String TITLE_NAME = "Select Product Vendor and Store";
  private final HibernateDataManagerDyn hdm = new HibernateDataManagerDyn();

  /**
   * Creates new form SelectVendorAndStoreJPanel
   */
  public SelectVendorAndStoreJPanel() {
    initComponents();
    List<ProductVendor> vendors = hdm.getAllProductVendors();
    Collections.sort(vendors);
    
    for (ProductVendor v : vendors)
    {
      ((DefaultComboBoxModel)jComboBoxProductVendors.getModel()).addElement(v);
    }

    List<Store> stores = hdm.getAllStores();
    Collections.sort(stores);
    for (Store s : stores)
    {
      ((DefaultComboBoxModel)jComboBoxStores.getModel()).addElement(s);
    }    
  }
  
  /**
   * Creates new form SelectVendorAndStoreJPanel
   * @param isAllStores true to include all stores option.
   */
  public SelectVendorAndStoreJPanel(final boolean isAllStores) {
    this();
    
    // If we want to allow all stores to be selected, we will
    // add it here and set it as the default.
    if (isAllStores)
    {
      Store allStore = new Store(Utils.ALL_STORES_MSG);
      ((DefaultComboBoxModel)jComboBoxStores.getModel()).addElement(allStore);
      jComboBoxStores.setSelectedItem(allStore);
    }
  }  

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    jComboBoxProductVendors = new javax.swing.JComboBox();
    jLabel2 = new javax.swing.JLabel();
    jComboBoxStores = new javax.swing.JComboBox();

    jLabel1.setText("Product Vendor");

    jLabel2.setText("Store");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(jComboBoxProductVendors, 0, 311, Short.MAX_VALUE)
          .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jComboBoxStores, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jComboBoxProductVendors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel2)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jComboBoxStores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JComboBox jComboBoxProductVendors;
  private javax.swing.JComboBox jComboBoxStores;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  // End of variables declaration//GEN-END:variables

  public ProductVendor getProductVendor()
  {
    return (ProductVendor)jComboBoxProductVendors.getSelectedItem();
  }

  public Store getStore()
  {
    return (Store)jComboBoxStores.getSelectedItem();
  }

}
