/*
 * Copyright (c) 2011, Fritz Feuerbacher.
 */
package com.feuersoft.imanager.ui;

import com.feuersoft.imanager.persistence.Customer;
import com.feuersoft.imanager.persistence.HibernateDataManagerDyn;
import java.util.Collections;
import java.util.List;
import javax.swing.DefaultComboBoxModel;

/**
 * @author Fritz Feuerbacher
 */
public class SelectCustomerJPanel extends javax.swing.JPanel {

    public static final String DISPLAY_NAME = "Select Customer";

    /** Creates new form SelectCustomerJPanel */
    public SelectCustomerJPanel()
    {
      initComponents();
      List<Customer> customers = (new HibernateDataManagerDyn()).getAllCustomers();
      Collections.sort(customers);
      for (Customer c : customers)
      {
        ((DefaultComboBoxModel)jComboBoxCustomers.getModel()).addElement(c);
      }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jComboBoxCustomers = new javax.swing.JComboBox();

      jComboBoxCustomers.setAutoscrolls(true);

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
      this.setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGap(20, 20, 20)
            .addComponent(jComboBoxCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(19, Short.MAX_VALUE))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGap(26, 26, 26)
            .addComponent(jComboBoxCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(20, Short.MAX_VALUE))
      );
   }// </editor-fold>//GEN-END:initComponents


   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JComboBox jComboBoxCustomers;
   // End of variables declaration//GEN-END:variables

  public Customer getCustomer()
  {
    return (Customer)jComboBoxCustomers.getSelectedItem();
  }
}
