/*
 * Copyright (c) 2011, Fritz Feuerbacher.
 */
package com.feuersoft.imanager.ui;

import com.feuersoft.imanager.persistence.HibernateDataManagerDyn;
import com.feuersoft.imanager.persistence.UnitMeasure;
import java.util.Collections;
import java.util.List;
import javax.swing.DefaultComboBoxModel;

/**
 * @author Fritz Feuerbacher
 */
public class SelectUnitMeasureJPanel extends javax.swing.JPanel {

    public static final String DISPLAY_NAME = "Select Unit of Measure";

    /** Creates new form SelectUnitMeasureJPanel */
    public SelectUnitMeasureJPanel() {
        initComponents();
        List<UnitMeasure> units = (new HibernateDataManagerDyn()).getAllUnitMeasures();
        Collections.sort(units);
        for (UnitMeasure u : units)
        {
          ((DefaultComboBoxModel)jComboBoxUnitOfMeasures.getModel()).addElement(u);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jComboBoxUnitOfMeasures = new javax.swing.JComboBox();

      jComboBoxUnitOfMeasures.setAutoscrolls(true);

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
      this.setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGap(33, 33, 33)
            .addComponent(jComboBoxUnitOfMeasures, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(35, Short.MAX_VALUE))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGap(27, 27, 27)
            .addComponent(jComboBoxUnitOfMeasures, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(28, Short.MAX_VALUE))
      );
   }// </editor-fold>//GEN-END:initComponents


   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JComboBox jComboBoxUnitOfMeasures;
   // End of variables declaration//GEN-END:variables

  public UnitMeasure getUnitMeasure()
  {
    return (UnitMeasure)jComboBoxUnitOfMeasures.getSelectedItem();
  }
}
